routes/web.php
<?php

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
Route::get('confirmation/{token}', 'Auth\RegisterController@confirmation')
    ->name('confirmation');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');;
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Social authentication
Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider')->name('provider');
Route::get('{provider}/callback', 'Auth\RegisterController@handleProviderCallback');

Route::get('/', function () {
    return view('welcome');
});

Route::resource('audits', 'AuditController');

Route::get('/chat', function () {
    return view('chat');
})->middleware("auth");

Route::get('/messages', function () {
    return App\Message::with('user')->get();
})->middleware('auth');

Route::post('/messages', function () {
    $user = Auth::user();
    $message = $user->messages()->create([
      "message" => request()->get('message')
    ]);

    broadcast(new MessagePosted($message, $user))->toOthers();

    return ['status' => 'ok'];
})->middleware('auth');


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::post('/file', function(Request $request){
  if ($request->hasFile('file')) {
    $file = $request->file('file');
    $ext  = $file->guessClientExtension();

    $path = $file->storeAs('files/', 'avatar.'.$ext);
    // $path = $request->file('file')->store('files');

    return $path;
  }else{
    return "no file";
  }
});

Route::group(['namespace' => 'Backend', 'middleware' => 'auth'], function (){
    /* Rutas para controlador AccountsController */
    Route::get('my-account', 'AccountsController@getIndex')->name('account');
    Route::post('update-account', 'AccountsController@postUpdate')->name('update_account');
    Route::post('drop-account', 'AccountsController@postDropOut')->name('drop_account');
});

// Usuario - Perfil
Route::resource('user', 'UsersController');

// Employee's routes
Route::resource('employees', 'EmployeesController');
Route::get('employees/{id}/destroy',[
    'uses' => 'EmployeesController@destroy',
    'as' => 'employees.destroy'
]);

Route::resource('employees-project', 'EmployeesProjectController');


Route::resource('employees-department', 'EmployeesDepartmentController');

// Profile picture route
Route::get('storage/app/public/profile_pictures/{folder}/{image}', function($folder = null, $image = null) {
	$path = storage_path().'/app/public/profile_pictures/'.$folder.'/'.$image;
	return Response::download($path);
})->name('image');

/* Ruta de departamentos*/
Route::resource('department', 'DepartmentsController');
    Route::get('department/{id}/destroy',[
          'uses' => 'DepartmentsController@destroy', 
          'as' => 'department.destroy'
        ]);

/* Ruta de cargos */
Route::resource('charge', 'ChargesController');
Route::get('charge/{id}/destroy',[
  'uses' => 'ChargesController@destroy',
  'as' => 'charge.destroy'
]);

/* Ruta de Proyectos */
Route::resource('project', 'ProjectsController');
Route::get('project/{id}/destroy',[
    'uses' => 'ProjectsController@destroy',
    'as' => 'project.destroy'
]);
// GENERAR PDF - ILDEMAR
Route::get('project/{id}/generatePDF',[
    'uses' => 'ProjectsController@generatePDF',
    'as' => 'project.pdf'
]);

/* Ruta de Tareas */
Route::resource('task', 'TasksController');
Route::get('task/{id}/destroy',[
    'uses' => 'TasksController@destroy',
    'as' => 'task.destroy'
]);

/* Ruta de Documents */

Route::resource('documents', 'DocumentsController');

// PDF
Route::get("/documents/pdf/constancia", function(){

  $pdf = PDF::loadView('documents.pdf');
  return $pdf->stream();

});

Route::post('/file', function(Request $request){
  if ($request->hasFile('file')) {
    $file = $request->file('file');
    $ext  = $file->guessClientExtension();

    $path = $file->storeAs('files/', 'avatar.'.$ext);
    // $path = $request->file('file')->store('files');

    return $path;
  }else{
    return "no file";
  }
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Task extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'project_id',
        'employee_id',
        'start',
        'end'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function employee()
    {
        return $this->belongsTo('App\Models\Employee');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function project()
    {
        return $this->belongsTo('App\Models\Project');
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use App\Models\Project;
use App\Models\Task;
use Illuminate\Http\Request;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // todas las tareas
        $tasks = Task::paginate();
        return view('tasks.index', compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // todos los proyectos
        $projects  = Project::all();
        // todos los empleados
        $employees = Employee::all();

        return view('tasks.create', compact('projects', 'employees'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validation
        $this->validate($request, [
            'name'        => 'required',
            'description' => 'required',
            'project_id'  => 'required',
            'employee_id' => 'required',
        ]);

        $task = new Task();
        $task->fill($request->all());

        // guardar
        if ($task->save())
        {
            $request->session()->flash('message', [
                'alert' => 'success', 'text' => trans('dashboard.messages.created')
            ]);

            return redirect()->route('task.index');
        }
        else
        {
            // todos los proyectos
            $projects  = Project::all();
            // todos los empleados
            $employees = Employee::all();

            return view('tasks.create', compact('projects', 'employees'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // información de una tarea
        $task = Task::find($id);

        return view('tasks.view', compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // información de una tarea
        $task = Task::find($id);

        // proyectos
        $projects = Project::all();

        // empleados
        $employees = Employee::all();

        return view('tasks.edit', compact('task', 'projects', 'employees'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // validation
        $this->validate($request, [
            'name'        => 'required',
            'description' => 'required',
            'project_id'  => 'required',
            'employee_id' => 'required',
        ]);

        $task = Task::find($id);
        $task->fill($request->all());

        // guardar
        if ($task->save())
        {
            $request->session()->flash('message', [
                'alert' => 'success', 'text' => trans('dashboard.messages.created')
            ]);

            return redirect()->route('task.index');
        }
        else
        {
            // todos los proyectos
            $projects  = Project::all();
            // todos los empleados
            $employees = Employee::all();

            return view('tasks.edit', compact('projects', 'employees'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Task::destroy($id);
        return redirect('task');
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app')
@section('content')

    {!! Form::open(['route' => 'task.store', 'method'=>'POST']) !!}
    {{ csrf_field() }}

    <div class="page-header">
        <h1><img src="assets/images/ICON-ACTIVIDADES.png" height="45"> @lang('common.register')</h1>
    </div><!-- /.page-header -->

    <div class="row">
        {{--Task name--}}
        <div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            <label class="col-sm-3 control-label" for="name">@lang('tasks.name')</label>
            <div class="col-sm-8">
                <div class="input-group">
                    {!!Form::text('name', null, ['class'=>'form-control', 'id' => 'name', 'placeholder' => trans('tasks.name_placeholder'), 'required']) !!}
                    <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
                </div>
            </div>
            @if ($errors->has('name'))
                <div class="col-sm-8 col-sm-offset-3">
            <span class="help-block">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
                </div>
            @endif
        </div>

        {{--Task project--}}
        <div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('project_id') ? ' has-error' : '' }}">
            <label class="col-sm-3 control-label" for="name">@lang('tasks.project')</label>
            <div class="col-sm-8">
                <div class="input-group">
                    <select class="form-control" name="project_id" id="project_id" tabindex="-1" style="" required>
                        <option>@lang('tasks.select_project')</option>
                        @foreach($projects as $project)
                            <option value="{{ $project->id }}">{{ $project->name }}</option>
                        @endforeach
                    </select>

                    <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
                </div>
            </div>
            @if ($errors->has('project_id'))
                <div class="col-sm-8 col-sm-offset-3">
            <span class="help-block">
                <strong>{{ $errors->first('project_id') }}</strong>
            </span>
                </div>
            @endif
        </div>
    </div>

    <div class="row">
        {{--Task description--}}
        <div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('description') ? ' has-error' : '' }}">
            <label class="col-sm-3 control-label" for="name">@lang('tasks.description')</label>
            <div class="col-sm-8">
                <div class="input-group">
                    {!! Form::textarea('description', null, ['class'=>'form-control','placeholder'=>trans('tasks.description_placeholder'), 'required', 'rows' => '3'])!!}
                    <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
                </div>
            </div>
            @if ($errors->has('description'))
                <div class="col-sm-8 col-sm-offset-3">
            <span class="help-block">
                <strong>{{ $errors->first('description') }}</strong>
            </span>
                </div>
            @endif
        </div>

        {{--Task employee--}}
        <div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('employee_id') ? ' has-error' : '' }}">
            <label class="col-sm-3 control-label" for="name">@lang('tasks.employee')</label>
            <div class="col-sm-8">
                <div class="input-group">
                    <select class="form-control" name="employee_id" id="employee_id" tabindex="-1" style="" required>
                        <option>@lang('tasks.select_employee')</option>
                        @foreach($employees as $employee)
                            <option value="{{ $employee->id }}">{{ $employee->first_name }} {{ $employee->last_name }}</option>
                        @endforeach
                    </select>

                    <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
                </div>
            </div>
            @if ($errors->has('employee_id'))
                <div class="col-sm-8 col-sm-offset-3">
            <span class="help-block">
                <strong>{{ $errors->first('employee_id') }}</strong>
            </span>
                </div>
            @endif
        </div>
    </div>

    <div class="row">
        {{--Task dates--}}
        <div class="col-sm-6 col-md-6 col-lg-6 form-group">
            <label class="col-sm-3 control-label">Tiempo estimado</label>
            <div class="col-sm-8">
                <div class="input-daterange input-group" id="datepicker">
                    {!!Form::text('start', null, ['class' => 'input-sm form-control', 'id' => 'start', 'placeholder' => 'Desde']) !!}
                    <span class="input-group-addon">-</span>
                    {!!Form::text('end', null, ['class' => 'input-sm form-control', 'id' => 'end', 'placeholder' => 'Hasta']) !!}

                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        {!!Form::submit('Guardar', ['class'=>'btn btn-crear'])!!}
        <a href="{{ route('task.index') }}" class="btn btn-crear">Cancelar</a>
    </div>



@section('content_extra')

@endsection

{!! Form::close() !!}

@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')
@section('content')

    {!! Form::open(['route' => ['task.update', $task->id], 'method'=>'PUT']) !!}
    {{ csrf_field() }}

    <div class="page-header">
        <h1><img src="assets/images/ICON-ACTIVIDADES.png" height="45"> @lang('common.edit')</h1>
    </div><!-- /.page-header -->

    <div class="row">
        {{--Task name--}}
        <div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            <label class="col-sm-3 control-label" for="name">@lang('tasks.name')</label>
            <div class="col-sm-8">
                <div class="input-group">
                    {!!Form::text('name', $task->name, ['class'=>'form-control', 'id' => 'name', 'placeholder' => trans('tasks.name_placeholder'), 'required']) !!}
                    <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
                </div>
            </div>
            @if ($errors->has('name'))
                <div class="col-sm-8 col-sm-offset-3">
            <span class="help-block">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
                </div>
            @endif
        </div>

        {{--Task project--}}
        <div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('project_id') ? ' has-error' : '' }}">
            <label class="col-sm-3 control-label" for="name">@lang('tasks.project')</label>
            <div class="col-sm-8">
                <div class="input-group">
                    <select class="form-control" name="project_id" id="project_id" tabindex="-1" style="" required>
                        <option>@lang('tasks.select_project')</option>
                        @foreach($projects as $project)
                            <option value="{{ $project->id }}" {{ $project->id == $task->project_id ? 'selected' : '' }}>{{ $project->name }}</option>
                        @endforeach
                    </select>

                    <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
                </div>
            </div>
            @if ($errors->has('project_id'))
                <div class="col-sm-8 col-sm-offset-3">
            <span class="help-block">
                <strong>{{ $errors->first('project_id') }}</strong>
            </span>
                </div>
            @endif
        </div>
    </div>

    <div class="row">
        {{--Task description--}}
        <div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('description') ? ' has-error' : '' }}">
            <label class="col-sm-3 control-label" for="name">@lang('tasks.description')</label>
            <div class="col-sm-8">
                <div class="input-group">
                    {!! Form::textarea('description', $task->description, ['class'=>'form-control','placeholder'=>trans('tasks.description_placeholder'), 'required', 'rows' => '3'])!!}
                    <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
                </div>
            </div>
            @if ($errors->has('description'))
                <div class="col-sm-8 col-sm-offset-3">
            <span class="help-block">
                <strong>{{ $errors->first('description') }}</strong>
            </span>
                </div>
            @endif
        </div>

        {{--Task employee--}}
        <div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('employee_id') ? ' has-error' : '' }}">
            <label class="col-sm-3 control-label" for="name">@lang('tasks.employee')</label>
            <div class="col-sm-8">
                <div class="input-group">
                    <select class="form-control" name="employee_id" id="employee_id" tabindex="-1" style="" required>
                        <option>@lang('tasks.select_employee')</option>
                        @foreach($employees as $employee)
                            <option value="{{ $employee->id }}" {{ $employee->id == $task->employee_id ? 'selected' : '' }}>{{ $employee->first_name }} {{ $employee->last_name }}</option>
                        @endforeach
                    </select>

                    <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
                </div>
            </div>
            @if ($errors->has('employee_id'))
                <div class="col-sm-8 col-sm-offset-3">
            <span class="help-block">
                <strong>{{ $errors->first('employee_id') }}</strong>
            </span>
                </div>
            @endif
        </div>
    </div>

    <div class="row">
        {{--Task dates--}}
        <div class="col-sm-6 col-md-6 col-lg-6 form-group">
            <label class="col-sm-3 control-label">Tiempo estimado</label>
            <div class="col-sm-8">
                <div class="input-daterange input-group" id="datepicker">
                    {!!Form::text('start', $task->start, ['class' => 'input-sm form-control', 'id' => 'start', 'placeholder' => 'Desde']) !!}
                    <span class="input-group-addon">-</span>
                    {!!Form::text('end', $task->end, ['class' => 'input-sm form-control', 'id' => 'end', 'placeholder' => 'Hasta']) !!}

                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        {!!Form::submit('Guardar', ['class'=>'btn btn-crear'])!!}
        <a href="{{ route('task.index') }}" class="btn btn-crear">Cancelar</a>
    </div>

@section('content_extra')

@endsection

{!! Form::close() !!}

@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="page-header">
        <h1><img src="assets/images/ICON-ACTIVIDADES.png" height="45">@lang('tasks.tasks')</h1>
    </div><!-- /.page-header -->

    <div class="row">

        <div class="col-xs-12 bord-table">
            <div class="table-responsive">

                <table class="table table-hover">
                    <thead class="text-primary doc">
                    <tr>
                        <th class="first-th">Nombre</th>
                        <th>Descripción</th>
                        <th>Proyecto</th>
                        <th>Empleado</th>
                        <th class="ultim-th">Acción</th>
                    </tr>
                    </thead>
                    <tbody align="center">
                    @foreach(\App\Models\Task::all() as $task)
                        <tr class="tr">
                            <td><a href="{{ url('task/'.$task->id) }}">{{ $task->name }}</a></td>
                            <td>{{ $task->description }}</td>
                            <td>{{ $task->project->name }}</td>
                            <td>{{ $task->employee->first_name }} {{ $task->employee->last_name }}</td>
                            <td>
                                <a href="{{ url('task/'.$task->id.'/edit') }}">
                                    <span class="btn btn-edit fa fa-pencil-square-o btn-secundary" data-placement="bottom" title="Editar"></span></a>
                                </a>
                                <a href="{{ route('task.destroy', $task->id) }} " onclick="return confirm('¿Desea eliminar esta tarea?');">
                                    <span class="btn btn-eliminar fa fa-trash-o" data-toggle="tooltip" data-placement="bottom" title="Eliminar"></span>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                </br>
                <div align="left">
                    <i class="fa fa-bar-chart"></i>
                    <span id="products-total">{{ $tasks->total() }}</span>
                    registros | página {{ $tasks->currentPage() }}
                    de {{ $tasks->lastPage() }}
                </div>
            </div>
        </div>
    </div>


@endsection

@section('content_extra')
    <div align="center">
        <a href="{{ route('task.create') }}">
            <button class="btn btn-crear">Crear</button>
        </a>
    </div>
@endsection

resources/views/tasks/view.blade.php
@extends('layouts.app')
@section('content')



    <div class="page-header">
        <h1><img src="assets/images/ICON-ACTIVIDADES.png" height="45"> @lang('tasks.detail')</h1>
    </div><!-- /.page-header -->

    <div class="panel panel-default bord-table">
        <!-- Default panel contents -->
        <div class="panel-heading"><th class="first-th">@lang('projects.name'):</th> {{ $task->name }}</div>
        <div class="panel-body">
            <b>@lang('tasks.description'):</b>
            <p>{{ $task->description }}</p>
        </div>

        <!-- List group -->
        <ul class="list-group">
            <li class="list-group-item"><b>@lang('tasks.project'):</b><a href="{{ url('project/'.$task->project->id) }}"> {{ $task->project->name }}</a></li>
            <li class="list-group-item"><b>@lang('tasks.employee'):</b><a href="{{ url('employees/'.$task->employee->id) }}"> {{ $task->employee->first_name }} {{ $task->employee->last_name }}</a></li>
            <li class="list-group-item"><b>@lang('tasks.star_date'):</b> {{ $task->start }}</li>
            <li class="list-group-item"><b>@lang('tasks.end_date'):</b> {{ $task->end }}</li>
        </ul>
    </div>


    <div class="form-group">
        <a href="{{ url('task/'.$task->id.'/edit') }}" class="btn btn-crear">Editar</a>
        <a href="{{ route('task.destroy', $task->id) }}" class="btn btn-crear" onclick="return confirm('¿Desea eliminar esta tarea?');">Eliminar</a>
        <a href="{{ url('/task') }}" class="btn btn-crear">Volver</a>
    </div>

@section('content_extra')

@endsection

@endsection