routes/web.php
<?php

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
Route::get('confirmation/{token}', 'Auth\RegisterController@confirmation')
    ->name('confirmation');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');;
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Social authentication
Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider')->name('provider');
Route::get('{provider}/callback', 'Auth\RegisterController@handleProviderCallback');

Route::get('/', function () {
    return view('welcome');
});

Route::resource('audits', 'AuditController');

Route::get('/chat', function () {
    return view('chat');
})->middleware("auth");

Route::get('/messages', function () {
    return App\Message::with('user')->get();
})->middleware('auth');

Route::post('/messages', function () {
    $user = Auth::user();
    $message = $user->messages()->create([
      "message" => request()->get('message')
    ]);

    broadcast(new MessagePosted($message, $user))->toOthers();

    return ['status' => 'ok'];
})->middleware('auth');


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::post('/file', function(Request $request){
  if ($request->hasFile('file')) {
    $file = $request->file('file');
    $ext  = $file->guessClientExtension();

    $path = $file->storeAs('files/', 'avatar.'.$ext);
    // $path = $request->file('file')->store('files');

    return $path;
  }else{
    return "no file";
  }
});

Route::group(['namespace' => 'Backend', 'middleware' => 'auth'], function (){
    /* Rutas para controlador AccountsController */
    Route::get('my-account', 'AccountsController@getIndex')->name('account');
    Route::post('update-account', 'AccountsController@postUpdate')->name('update_account');
    Route::post('drop-account', 'AccountsController@postDropOut')->name('drop_account');
});

// Usuario - Perfil
Route::resource('user', 'UsersController');

// Employee's routes
Route::resource('employees', 'EmployeesController');
Route::get('employees/{id}/destroy',[
    'uses' => 'EmployeesController@destroy',
    'as' => 'employees.destroy'
]);

Route::resource('employees-project', 'EmployeesProjectController');


Route::resource('employees-department', 'EmployeesDepartmentController');

// Profile picture route
Route::get('storage/app/public/profile_pictures/{folder}/{image}', function($folder = null, $image = null) {
	$path = storage_path().'/app/public/profile_pictures/'.$folder.'/'.$image;
	return Response::download($path);
})->name('image');

/* Ruta de departamentos*/
Route::resource('department', 'DepartmentsController');
    Route::get('department/{id}/destroy',[
          'uses' => 'DepartmentsController@destroy', 
          'as' => 'department.destroy'
        ]);

/* Ruta de cargos */
Route::resource('charge', 'ChargesController');
Route::get('charge/{id}/destroy',[
  'uses' => 'ChargesController@destroy',
  'as' => 'charge.destroy'
]);

/* Ruta de Proyectos */
Route::resource('project', 'ProjectsController');
Route::get('project/{id}/destroy',[
    'uses' => 'ProjectsController@destroy',
    'as' => 'project.destroy'
]);
// GENERAR PDF - ILDEMAR
Route::get('project/{id}/generatePDF',[
    'uses' => 'ProjectsController@generatePDF',
    'as' => 'project.pdf'
]);

/* Ruta de Tareas */
Route::resource('task', 'TasksController');
Route::get('task/{id}/destroy',[
    'uses' => 'TasksController@destroy',
    'as' => 'task.destroy'
]);

/* Ruta de Documents */

Route::resource('documents', 'DocumentsController');

// PDF
Route::get("/documents/pdf/constancia", function(){

  $pdf = PDF::loadView('documents.pdf');
  return $pdf->stream();

});

Route::post('/file', function(Request $request){
  if ($request->hasFile('file')) {
    $file = $request->file('file');
    $ext  = $file->guessClientExtension();

    $path = $file->storeAs('files/', 'avatar.'.$ext);
    // $path = $request->file('file')->store('files');

    return $path;
  }else{
    return "no file";
  }
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'code',
        'first_name',
        'last_name',
        'email',
        'tasks',
        'skills',
        'hire_date',
        'phone',
        'identification',
        'profile_picture',
        'department_id',
        'charge_id',
        'status_id',
        'users_id'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function department()
    {
        return $this->belongsTo('App\Models\Department');
    }


    public function charge()
    {
        return $this->belongsTo('App\Models\Charge');
    }

    public function project()
    {
        return $this->belongsToMany('App\Models\Project');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tasks()
    {
        return $this->hasMany('App\Models\Task');
    }

    public function user()
    {
        return $this->belongsToMany('App\Models\User');
    }

}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use Illuminate\Http\Request;
use App\Models\Employee;
use App\Models\Department;
use App\Models\Charge;

class EmployeesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::paginate();
        return view('employees.index', ['employees' => $employees]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::all();
        $charges = Charge::all();
        return view('employees.create', compact('departments', 'charges'));
    }

    public function project()
    {
        $employees = Employee::paginate();
        return view('employees.index', ['employees' => $employees]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validation
        $this->validate($request, [
            'first_name'     => 'required',
            'last_name'      => 'required',
            'email'          => 'required',
            'tasks'          => 'required',
            'skills'         => 'required',
            'hire_date'      => 'required',
            'phone'          => 'required',
            'identification' => 'required',
            'department_id'  => 'required',
            'charge_id'      => 'required'
        ]);
        // Input values
        $employee = new Employee;


        // If input file has file, upload it
        if ($request->hasFile('profile_picture'))
        {
            $employee->fill($request->all());
            $employee->code            = $this->codeGenerator($request->email);
            $employee->profile_picture = $request->first_name.'_'.$request->last_name.'.jpg';
            // Upload Profile Picture
            $request->file('profile_picture')->storeAs('public/profile_pictures/'.$employee->code, $employee->profile_picture);
        }
        else
        {
            $employee->code = $this->codeGenerator($request->email);
            $employee->fill($request->all());
        }

        if ($employee->save())
        {
            $request->session()->flash('flash_message', 'Success!');
            return redirect('employees');
        }
        else
        {
            return view('employees.create', compact('employee'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $employee = Employee::find($id);
        $tasks = Employee::find($id)->tasks()->get();

        //dd($tasks);

        return view('employees.view', compact('employee', 'tasks'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee    = Employee::find($id);
        $departments = Department::all();
        $charges     = Charge::all();

        return view('employees.edit', compact('employee', 'departments', 'charges'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Validations
        $this->validate($request, [
            'first_name'     => 'required',
            'last_name'      => 'required',
            'email'          => 'required',
            'tasks'          => 'required',
            'skills'         => 'required',
            'hire_date'      => 'required',
            'phone'          => 'required',
            'identification' => 'required'
        ]);

        $employee = Employee::find($id);

        // If input file has file, upload it
        if ($request->hasFile('profile_picture'))
        {
            $employee->fill($request->all());
            $employee->profile_picture = $request->first_name.'_'.$request->last_name.'.jpg';
            // upload picture
            $request->file('profile_picture')->storeAs('public/profile_pictures/'.$employee->code, $employee->profile_picture);
        }
        else
        {
            $employee->fill($request->all());
        }

        if ($employee->save())
        {
            $request->session()->flash('flash_message', 'Success!');
            return redirect('employees');
        }
        else
        {
            return view('employees.edit', ['employee' => $employee]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $employee = Employee::find($id);
        $employee->delete();

        return redirect('employees');
    }

    /**
     * Generate random code from user email
     *
     * @param  string $email
     * @return string User code
     */
    private function codeGenerator($email)
    {
        $key = '';
        $length = 5;
        $pattern = '0123456789qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM';
        $max = strlen($pattern)-1;

        for($i = 0; $i < $length; $i++)
        {
            $key .= $pattern{mt_rand(0, $max)};
        }
        return substr($email, 0, 4).'-'.$key;
    }
}

resources/views/employees/create.blade.php
@extends ('layouts.app')

@section('content')


<div class="page-header">
        <h1><img src="assets/images/ICON-ACTIVIDADES.png" height="45"> @lang('common.register')</h1>
    </div><!-- /.page-header -->


<div class="container">
	
	<form action="{{ url('employees') }}" method="POST" class="form-horizontal" enctype="multipart/form-data">
		
		{{ csrf_field() }}

<div class="row">
 <div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.first_name')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	         <input type="text" class="form-control" name="first_name" placeholder="@lang('employee.first_name_placeholder')">
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('first_name'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('first_name') }}</strong>
	        </span>
	    </div>
	@endif
  </div>


<div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('last_name') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.last_name')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	         <input type="text" class="form-control" name="last_name" placeholder="@lang('employee.last_name_placeholder')">
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('last_name'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('last_name') }}</strong>
	        </span>
	    </div>
	@endif
    </div>
  </div>

<div class="row">
 <div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('email') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.email')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	         <input type="email" class="form-control" name="email" placeholder="@lang('employee.email_placeholder')">
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('email'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('email') }}</strong>
	        </span>
	    </div>
	@endif
  </div>	

<div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('hire_date') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.hire_date')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	        <input type="date" class="form-control" name="hire_date" placeholder="Contratado"></textarea>
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('hire_date'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('hire_date') }}</strong>
	        </span>
	    </div>
	@endif
  </div>	
</div>

<div class="row">
 <div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.phone')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	        <input type="number" class="form-control" name="phone" placeholder="@lang('employee.phone_placeholder')">
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('phone'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('phone') }}</strong>
	        </span>
	    </div>
	@endif
  </div>	

<div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('identification') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.identification')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	          <input type="text" class="form-control" name="identification" placeholder="@lang('employee.identification_placeholder')">
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('identification'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('identification') }}</strong>
	        </span>
	    </div>
	@endif
  </div>	
</div>

<div class="row">
<div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('tasks') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.tasks')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	         <textarea name="tasks" rows="4" placeholder="@lang('employee.tasks_placeholder')" class="form-control"></textarea>
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('tasks'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('tasks') }}</strong>
	        </span>
	    </div>
	@endif
  </div>	

<div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('skills') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.skills')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	         <textarea name="skills" rows="4" placeholder="@lang('employee.skills')" class="form-control"></textarea>
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('skills'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('skills') }}</strong>
	        </span>
	    </div>
	@endif
  </div>	
</div>


<div class="row">
<div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('department_id') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.department')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	         <select class="form-control" name="department_id" id="department" required>
	                <option>@lang('employee.select_department')</option>
				@foreach($departments as $department)
					<option value="{{ $department->id }}">{{ $department->name }}</option>
				@endforeach
			</select>
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('department_id'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('department_id') }}</strong>
	        </span>
	    </div>
	@endif
  </div>

<div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('charge_id') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.charge')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	         <select class="form-control" name="charge_id" id="charge_id" required>
	                <option>@lang('employee.select_charge')</option>
				@foreach($charges as $charge)
					<option value="{{ $charge->id }}">{{ $charge->name }}</option>
				@endforeach
			</select>
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('charge_id'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('charge_id') }}</strong>
	        </span>
	    </div>
	@endif
  </div>
</div>

<div class="row">
<div class="col-sm-6 col-md-6 col-lg-6 form-group">
   <label class="col-sm-3 control-label" for="profile_picture">Foto</label>
    <div class="col-sm-8">
    	  <div class="input-group">
			<input type="file" id="profile_picture" name="profile_picture">
		 </div>
    </div>
  </div>
</div>
		

<div class="form-group">
   <input type="submit" class="btn btn-crear" value="Guardar">
		&nbsp;
	<a href="{{ route('employees.index') }}" class="btn btn-crear">Cancelar</a>
 </div>
</form>




@endsection

resources/views/employees/edit.blade.php
@extends ('layouts.app')

@section('content')

<div class="page-header">
        <h1><img src="assets/images/ICON-ACTIVIDADES.png" height="45"> @lang('common.edit')</h1>
    </div><!-- /.page-header -->



<div class="container">
	
	<form action="{{ route('employees.update', $employee->id) }}" method="post" enctype="multipart/form-data">
		
		{{ csrf_field() }}

		<input type="hidden" name="_method" value="PUT">

		
<div class="row">
 <div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.first_name')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	         <input type="text" class="form-control" name="first_name" placeholder="@lang('employee.first_name_placeholder')" value="{{ $employee->first_name }}">
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('first_name'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('first_name') }}</strong>
	        </span>
	    </div>
	@endif
  </div>


<div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('last_name') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.last_name')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	         <input type="text" class="form-control" name="last_name" placeholder="@lang('employee.last_name_placeholder')" value="{{ $employee->last_name }}">
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('last_name'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('last_name') }}</strong>
	        </span>
	    </div>
	@endif
    </div>
  </div>

<div class="row">
 <div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('email') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.email')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	         <input type="email" class="form-control" name="email" placeholder="@lang('employee.email_placeholder')" value="{{ $employee->email }}">
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('email'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('email') }}</strong>
	        </span>
	    </div>
	@endif
  </div>	

<div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('hire_date') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.hire_date')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	        <input type="date" class="form-control" name="hire_date" value="{{ $employee->hire_date }}" >
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('hire_date'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('hire_date') }}</strong>
	        </span>
	    </div>
	@endif
  </div>	
</div>

<div class="row">
 <div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.phone')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	        <input type="number" class="form-control" name="phone" placeholder="@lang('employee.phone_placeholder')" value="{{ $employee->phone }}">
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('phone'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('phone') }}</strong>
	        </span>
	    </div>
	@endif
  </div>	

<div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('identification') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.identification')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	          <input type="text" class="form-control" name="identification" placeholder="@lang('employee.identification_placeholder')" value="{{ $employee->identification }}">
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('identification'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('identification') }}</strong>
	        </span>
	    </div>
	@endif
  </div>	
</div>

<div class="row">
<div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('tasks') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.tasks')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	         <textarea name="tasks" rows="4" placeholder="@lang('employee.tasks_placeholder')" class="form-control" >{{ $employee->tasks }}</textarea>
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('tasks'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('tasks') }}</strong>
	        </span>
	    </div>
	@endif
  </div>	

<div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('skills') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.skills')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	         <textarea name="skills" rows="4" placeholder="@lang('employee.skills')" class="form-control">{{ $employee->skills }}</textarea>
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('skills'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('skills') }}</strong>
	        </span>
	    </div>
	@endif
  </div>	
</div>


<div class="row">
<div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('department_id') ? ' has-error' : '' }}">
    <label class="col-sm-3 control-label" for="name">@lang('employee.department')</label>
       <div class="col-sm-8">
    	  <div class="input-group">
	         <select class="form-control" name="department_id" id="department" required>
	                <option>Seleccionar Departamento</option>
				@foreach($departments as $department)
					<option value="{{ $department->id }}" {{ $department->id == $employee->department_id ? 'selected' : '' }}>{{ $department->name }}</option>
				@endforeach
			</select>
			 <span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
	    </div>
    </div>
	@if ($errors->has('department_id'))
		<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('department_id') }}</strong>
	        </span>
	    </div>
	@endif
  </div>

	<div class="col-sm-6 col-md-6 col-lg-6 form-group{{ $errors->has('charge_id') ? ' has-error' : '' }}">
		<label class="col-sm-3 control-label" for="name">@lang('employee.charge')</label>
		<div class="col-sm-8">
			<div class="input-group">
				<select class="form-control" name="charge_id" id="charge_id" required>
					<option>@lang('employee.select_charge')</option>
					@foreach($charges as $charge)
						<option value="{{ $charge->id }}" {{ $charge->id == $employee->charge_id ? 'selected' : '' }}>{{ $charge->name }}</option>
					@endforeach
				</select>
				<span class="input-group-addon"><i class="fa fa-asterisk input-required"></i></span>
			</div>
		</div>
		@if ($errors->has('charge_id'))
			<div class="col-sm-8 col-sm-offset-3">
	        <span class="help-block">
	            <strong>{{ $errors->first('charge_id') }}</strong>
	        </span>
			</div>
		@endif
	</div>
</div>

<div class="col-sm-6 col-md-6 col-lg-6 form-group">
   <label class="col-sm-3 control-label" for="profile_picture">Foto</label>
    <div class="col-sm-8">
    	  <div class="input-group">
			<input type="file" id="profile_picture" name="profile_picture">
		 </div>
    </div>
  </div>
</div>
		

<div class="form-group">
   <input type="submit" class="btn btn-crear" value="Guardar">
		&nbsp;
	<a href="{{ route('employees.index') }}" class="btn btn-crear">Cancelar</a>
 </div>
</form>



@endsection