routes/web.php
<?php

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
Route::get('confirmation/{token}', 'Auth\RegisterController@confirmation')
    ->name('confirmation');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');;
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Social authentication
Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider')->name('provider');
Route::get('{provider}/callback', 'Auth\RegisterController@handleProviderCallback');

Route::get('/', function () {
    return view('welcome');
});

Route::resource('audits', 'AuditController');

Route::get('/chat', function () {
    return view('chat');
})->middleware("auth");

Route::get('/messages', function () {
    return App\Message::with('user')->get();
})->middleware('auth');

Route::post('/messages', function () {
    $user = Auth::user();
    $message = $user->messages()->create([
      "message" => request()->get('message')
    ]);

    broadcast(new MessagePosted($message, $user))->toOthers();

    return ['status' => 'ok'];
})->middleware('auth');


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::post('/file', function(Request $request){
  if ($request->hasFile('file')) {
    $file = $request->file('file');
    $ext  = $file->guessClientExtension();

    $path = $file->storeAs('files/', 'avatar.'.$ext);
    // $path = $request->file('file')->store('files');

    return $path;
  }else{
    return "no file";
  }
});

Route::group(['namespace' => 'Backend', 'middleware' => 'auth'], function (){
    /* Rutas para controlador AccountsController */
    Route::get('my-account', 'AccountsController@getIndex')->name('account');
    Route::post('update-account', 'AccountsController@postUpdate')->name('update_account');
    Route::post('drop-account', 'AccountsController@postDropOut')->name('drop_account');
});

// Usuario - Perfil
Route::resource('user', 'UsersController');

// Employee's routes
Route::resource('employees', 'EmployeesController');
Route::get('employees/{id}/destroy',[
    'uses' => 'EmployeesController@destroy',
    'as' => 'employees.destroy'
]);

Route::resource('employees-project', 'EmployeesProjectController');


Route::resource('employees-department', 'EmployeesDepartmentController');

// Profile picture route
Route::get('storage/app/public/profile_pictures/{folder}/{image}', function($folder = null, $image = null) {
	$path = storage_path().'/app/public/profile_pictures/'.$folder.'/'.$image;
	return Response::download($path);
})->name('image');

/* Ruta de departamentos*/
Route::resource('department', 'DepartmentsController');
    Route::get('department/{id}/destroy',[
          'uses' => 'DepartmentsController@destroy', 
          'as' => 'department.destroy'
        ]);

/* Ruta de cargos */
Route::resource('charge', 'ChargesController');
Route::get('charge/{id}/destroy',[
  'uses' => 'ChargesController@destroy',
  'as' => 'charge.destroy'
]);

/* Ruta de Proyectos */
Route::resource('project', 'ProjectsController');
Route::get('project/{id}/destroy',[
    'uses' => 'ProjectsController@destroy',
    'as' => 'project.destroy'
]);
// GENERAR PDF - ILDEMAR
Route::get('project/{id}/generatePDF',[
    'uses' => 'ProjectsController@generatePDF',
    'as' => 'project.pdf'
]);

/* Ruta de Tareas */
Route::resource('task', 'TasksController');
Route::get('task/{id}/destroy',[
    'uses' => 'TasksController@destroy',
    'as' => 'task.destroy'
]);

/* Ruta de Documents */

Route::resource('documents', 'DocumentsController');

// PDF
Route::get("/documents/pdf/constancia", function(){

  $pdf = PDF::loadView('documents.pdf');
  return $pdf->stream();

});

Route::post('/file', function(Request $request){
  if ($request->hasFile('file')) {
    $file = $request->file('file');
    $ext  = $file->guessClientExtension();

    $path = $file->storeAs('files/', 'avatar.'.$ext);
    // $path = $request->file('file')->store('files');

    return $path;
  }else{
    return "no file";
  }
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    @include('layouts.header')
</head>

<body class="no-skin">
<div id="navbar" class="navbar navbar-default          ace-save-state">
    <div class="navbar-container ace-save-state" id="navbar-container">
        <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
            <span class="sr-only">Toggle sidebar</span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>
        </button>
        <div class="pull-right spacing-der">
            <div class="dropdown">
                <button class="btn dropdown-toggle log" type="button" data-toggle="dropdown"> {{ Auth::user()->name }}
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li><a href="{{ route('account') }}">Mi Cuenta</a></li>
                    <li>
                        <a href="{{ url('/logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            @lang('auth.logout')
                        </a>

                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </li>
                </ul>
                @foreach(App\Models\Employee::all() as $employee)
                    @foreach(App\Models\User::all() as $user)
                        @if($employee->first_name == $user->name)
                <img src="{{ route('image', ['folder' => $employee->code, 'image' => $employee->profile_picture]) }}" height="45" class="img-circle">
               </div>
                @endif
              @endforeach
            @endforeach
            </div>
    </div><!-- /.navbar-container -->
</div>
<div class="main-container ace-save-state" id="main-container">
    <script type="text/javascript">
        try{ace.settings.loadState('main-container')}catch(e){}
    </script>

    @include('layouts.navbar')

    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">@yield('breadcrumb')</div>

            <div class="page-content">
                @yield('content')
            </div>
        </div>
        @yield('content_extra')
    </div><!-- /.main-content -->

    @include('layouts.footer')
</div>
</body>
</html>

resources/views/layouts/app1.blade.php
<!DOCTYPE html>
<html>
<head>
	@include('layouts.header')
</head>
<body>
	@include('layouts.navbar')
	@yield('content')
	@include('layouts.footer')
</body>
</html>

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta charset="utf-8" />
		<title>Dashboard - SyxGem</title>

		<meta name="description" content="overview &amp; stats" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

		<!-- bootstrap & fontawesome -->
		<link rel="stylesheet" href="assets/css/bootstrap.min.css" />
		<link rel="stylesheet" href="assets/font-awesome/4.5.0/css/font-awesome.min.css" />
		<!-- <link rel="shortcut icon" href="../images/syxgem-icon.ico"> -->
		<link rel="shortcut icon" href="assets/images/syxgem-icon.ico">
		<!-- ace styles -->
		<link rel="stylesheet" href="assets/css/syx.min.css" class="ace-main-stylesheet" id="main-ace-style" />
	</head>

	<body class="no-skin">
		<div id="navbar" class="navbar navbar-default          ace-save-state">
			<div class="navbar-container ace-save-state" id="navbar-container">
				<button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
					<span class="sr-only">Toggle sidebar</span>

					<span class="icon-bar"></span>

					<span class="icon-bar"></span>

					<span class="icon-bar"></span>
				</button>

				<div class="navbar-header pull-left">
					<a href="index.html" class="navbar-brand">
						<small>
							<img src="assets/images/LOGO-SYXGEM-FINAL.png" height="35">
						</small>
					</a>
				</div>
				<div class="pull-right spacing-der">
					<a href="#" class="log-reg log">Iniciar Sesión</a>
					<a href="#" class="log-reg reg">Registrarse</a>
					<img src="assets/images/ICON-USER.png" height="45">
				</div>
			</div><!-- /.navbar-container -->
		</div>

		<div class="main-container ace-save-state" id="main-container">
			<script type="text/javascript">
				try{ace.settings.loadState('main-container')}catch(e){}
			</script>

			<div id="sidebar" class="sidebar responsive ace-save-state">
				<script type="text/javascript">
					try{ace.settings.loadState('sidebar')}catch(e){}
				</script>

			
				<ul class="nav nav-list">
					<li class="active li-alt">
						<a href="index.html" class="lev">
							<span class="menu-text"> Syxgem </span>
								<img src="assets/images/ICON-SYXIMAGO.png" alt="" height="35" align="right">	
						</a>

						<b class="arrow"></b>
					</li>

					<li class="">
						<a href="#" class="dropdown-toggle">
							<i class="menu-icon fa fa-suitcase"></i>
							<span class="menu-text">
								Proyectos
							</span>

							<b class="arrow fa fa-angle-down"></b>
						</a>

						<b class="arrow"></b>

						<ul class="submenu">

							<li class="">
								<a href="mis-proyectos.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Mis Proyectos
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="mis-tareas.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Mis Tareas
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="mi-calendario.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Mi Calendario
								</a>
							</li>
						</ul>
					</li>

					<li class="">
						<a href="departamentos.html" class="level-0">
							<i class="menu-icon fa fa-building-o"></i>
							<span class="menu-text"> Departamentos </span>
						</a>
					</li>

					<li class="">
						<a href="{{ url('charge') }}" class="level-0">
							<i class="menu-icon fa fa-calendar-check-o"></i>
							<span class="menu-text"> Cargos </span>
						</a>
						<b class="arrow"></b>
					</li>

					<li class="">
						<a href="documentos.html" class="level-0">
							<i class="menu-icon fa fa-folder"></i>
							<span class="menu-text"> Documentos </span>
						</a>

						<b class="arrow"></b>
					</li>

					<li class="li-alt">
						<a href="#" class="dropdown-toggle level-1">
							<span class="menu-text"> Chat </span>
							<i class="menu-icon fa fa-comments-o fa-lg"></i>							
							<b class="arrow fa fa-angle-down"></b>
						</a>
						<b class="arrow"></b>

						<ul class="submenu">
							<li class="">
								<a href="chat-individual.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Individual
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="chat-grupal.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Grupal
								</a>

								<b class="arrow"></b>
							</li>
						</ul>
					</li>

					<li class="li-alt">
						<a href="#" class="dropdown-toggle level-1">
							<span class="menu-text">
								Preferencias
							</span>
							<i class="menu-icon fa fa-cog fa-lg"></i>
							<b class="arrow fa fa-angle-down"></b>
						</a>

						<b class="arrow"></b>

						<ul class="submenu">
							<li class="">
								<a href="idioma.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Idioma
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="{{ route('user.index') }}">
									<i class="menu-icon fa fa-caret-right"></i>
									Perfil
								</a>

								<b class="arrow"></b>
							</li>
						</ul>
					</li>
				</ul><!-- /.nav-list -->

				
			</div>

			<div class="main-content">
				<div class="main-content-inner">
					<div class="breadcrumbs ace-save-state" id="breadcrumbs"></div>

					<div class="page-content">
						<div class="page-header">
							<h1>
								<img src="assets/images/ICON-ACTIVIDADES.png" height="45">
								Cargos
							</h1>
						</div><!-- /.page-header -->
						<div class="row">
								<div class="col-xs-12">
								<p align="justify">Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
								Soluta quam, ab earum dicta quae consequuntur illo voluptate!
								 Atque, aliquam rerum minus? Hic odio praesentium quod nihil 
								 voluptatem eos, cum itaque? Lorem ipsum dolor sit amet, 
								 consectetur adipisicing elit. 
								 Consequatur velit exercitationem veniam impedit soluta sit 
								 distinctio ipsa ex voluptatum, nulla ut sunt, nobis, nostrum 
								 delectus adipisci consequuntur, ullam eligendi. Voluptatibus.
								 </p>
								 <p align="justify">Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
									 Dolorem earum dolores eligendi eveniet? Maxime ex adipisci 
									 necessitatibus? Corporis, maiores explicabo ducimus, eius 
									 consequatur earum enim accusamus totam ipsa dicta quaerat. 
								</p>
								<p align="justify">Lorem ipsum dolor sit amet, consectetur 
									adipisicing elit. In perferendis ipsam nam aperiam maiores 
									magni consequuntur similique, amet impedit voluptas neque, 
									alias enim? Praesentium quos aut dolor excepturi deserunt 
									asperiores. Lorem ipsum dolor sit amet, consectetur adipisicing 
									elit. Quos minus tenetur numquam culpa, optio, recusandae tempore 
									delectus perspiciatis non? Reprehenderit sequi, vero dolorum 
									voluptatibus nulla praesentium ab? Architecto, non dignissimos. </p>
								</div>
							</div>
			</div><!-- /.main-content -->

			<footer class="footer">
				<div class="footer-inner">
					<div class="footer-content">
						<span class="bigger-120">
							<span class="purple bolder">SyxGem</span>
							Application &copy; 2017
						</span>

						&nbsp; &nbsp;
						<span class="action-buttons">
							<a href="#">
								<span>
									<img src="assets/images/ICON-FOLLOW5.png" alt="" height="30">
								</span>
							</a>

							<a href="#">
								<img src="assets/images/ICON-FOLLOW4.png" alt="" height="30">	
							</a>

							<a href="#">
								<img src="assets/images/ICON-FOLLOW3.png" alt="" height="30">
							</a>
						</span>
					</div>
				</div>
			</footer>

			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<script src="assets/js/jquery-2.1.4.min.js"></script>

		<script src="assets/js/bootstrap.min.js"></script>
		<script src="assets/js/syx.min.js"></script>
	</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="footer">
        <div class="footer-inner">
            <div class="footer-content">
                <span class="bigger-120">
                    <span class="purple bolder">SyxGem</span>
                    Application © 2017
                </span>

                &nbsp; &nbsp;
                <span class="action-buttons">
                    <a href="#">
                        <span>
                            <img src="{{ asset('assets/images/ICON-FOLLOW5.png') }}" alt="" height="30">
                        </span>
                    </a>

                    <a href="#">
                        <img src="{{ asset('assets/images/ICON-FOLLOW4.png') }}" alt="" height="30">   
                    </a>

                    <a href="#">
                        <img src="{{ asset('assets/images/ICON-FOLLOW3.png') }}" alt="" height="30">
                    </a>
                </span>
            </div>
        </div>
    </footer>

    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
    </a>
</div><!-- /.main-container -->

<!-- basic scripts -->

<script src="{{ asset('assets/js/jquery-2.1.4.min.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/syx.min.js') }}"></script>
{{--Chosen--}}
<script src="{{ asset('assets/js/chosen/chosen.jquery.js') }}"></script>
{{--Datepicker--}}
<script src="{{ asset('assets/js/datepicker/bootstrap-datepicker.js') }}"></script>

<script>
    $(document).ready(function() {
        $(".chosen-select").chosen();
        $(".chosen-select").trigger('chosen:updated');

        // datepicker
        $('.input-daterange').datepicker({
            keyboardNavigation: false,
            forceParse: false,
            autoclose: true,
            format: 'yyyy/mm/dd'
        });
    });

</script>

resources/views/layouts/head.blade.php
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sistema para la gestión de condominios y comunidades.">
    <meta name="keywords" content="Servicios, Condominio, Comunidades, Inmobiliaria">
    <meta name="author" content="Roldan Vargas, Gustavo Meza, Andrea Vargas, ISMCENTER">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="shortcut icon" type="image/png" href="{{ asset('static/images/favicon.png') }}" />
    <title>EDIFALIA</title>
	{{-- Bootstrap styles --}}
    {!! Html::style('static/bootstrap/css/bootstrap.min.css') !!}
    {{-- AdminLTE --}}
    {!! Html::style('static/adminlte/css/AdminLTE.min.css') !!}
    {!! Html::style('static/adminlte/css/skins/_all-skins.min.css') !!}
    {{-- Select2 (required) --}}
    {!! Html::style('static/select2/css/select2.css') !!}
    {!! Html::style('static/select2/css/select2-bootstrap.css') !!}

    {{-- Datatables (required) --}}
    {!! Html::style('static/datatables/extensions/TableTools/css/dataTables.tableTools.min.css') !!}
    {!! Html::style('static/datatables/css/dataTables.bootstrap.css') !!}
    {!! Html::style('static/datatables/extensions/Responsive/css/dataTables.responsive.css') !!}
    {{-- Bootstrap Switch (required) --}}
    {!! Html::style('static/bootstrap-switch/css/bootstrap-switch.min.css') !!}
    {{-- Toastr Notifications (required) --}}
    {!! Html::style('static/toastr/css/toastr.min.css') !!}
    {{-- Icon Pack from ionicons, icomoon and font-awesome --}}
    {!! Html::style('static/ionicons/css/ionicons.min.css') !!}
    {!! Html::style('static/font-awesome/css/font-awesome.min.css') !!}
    {{-- Custom apps styles --}}
    {!! Html::style('static/css/styles.custom.css') !!}
    {{-- OpenLayers Styles and Scripts --}}
    {!! Html::style('http://openlayers.org/en/v3.15.1/css/ol.css') !!}
    {!! Html::script('http://openlayers.org/en/v3.15.1/build/ol.js') !!}

    {{--iCheck for checkboxes and radio inputs--}}
    {!! Html::style('static/iCheck/all.css') !!}
    {{-- Toastr Notifications (required) --}}
    {!! Html::style('static/toastr/css/toastr.min.css') !!}
    {{-- Bootstrap-wysihtml5 is a javascript plugin --}}
    {!! Html::style('static/bootstrap3-wysihtml5-bower/dist/bootstrap3-wysihtml5.min.css') !!}
    {{-- Para styles extras --}}
    @section('styles')
    @show
</head>

resources/views/layouts/menu.blade.php
@extends('layouts.app')
@section('content')

<div class="row affix-row">
    <div class="col-sm-3 col-md-2 affix-sidebar">
    <div class="sidebar-nav">
  <div class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <span class="visible-xs navbar-brand">Sidebar menu</span>
    </div>
    <div class="navbar-collapse collapse sidebar-navbar-collapse">
      <ul class="nav navbar-nav" id="sidenav01">
        <li class="active">
          <a href="#" data-toggle="collapse" data-target="#toggleDemo0" data-parent="#sidenav01" class="collapsed">
          <h4>
          Syxgem
          <br>
          </h4>
          </a>

        </li>
        <li>
          <a href="#" data-toggle="collapse" data-target="#toggleDemo" data-parent="#sidenav01" class="collapsed">
          <span class="glyphicon glyphicon-cloud"></span> Proyectos<span class="caret pull-right"></span>
          </a>
          <div class="collapse" id="toggleDemo" style="height: 0px;">
            <ul class="nav nav-list">
              <li><a href="#">Mis Proyectos</a></li>
              <li><a href="#">Mis Tareas</a></li>
              <li><a href="#">Mi Calendario</a></li>
            </ul>
          </div>
        </li>
          <li><a href="{{ route('department.index')}}"><span class="glyphicon glyphicon-lock"></span> Departamentos</a></li>
        <li><a href="{{ route('charge.index')}}"><span class="glyphicon glyphicon-calendar"></span> Cargos <span class="badge pull-right">42</span></a></li>

        <li><a href="#"><span class="glyphicon glyphicon-inbox"></span> Documentos <span class="caret pull-right">42</span></a></li>

         <li class="active">
          <a href="#" data-toggle="collapse" data-target="#toggleDemo2" data-parent="#sidenav01" class="collapsed">
          <span class="glyphicon glyphicon-new-window"></span> Chat <span class="caret pull-right"></span>
          </a>
          <div class="collapse" id="toggleDemo2" style="height: 0px;">
            <ul class="nav nav-list">
              <li><a href="#">Individual</a></li>
              <li><a href="#">Grupal</a></li>
            </ul>
          </div>
        </li>

      
         <li class="active">
          <a href="#" data-toggle="collapse" data-target="#toggleDemo3" data-parent="#sidenav01" class="collapsed">
          <span class="glyphicon glyphicon-cog"></span> Preferencias <span class="caret pull-right"></span>
          </a>
          <div class="collapse" id="toggleDemo3" style="height: 0px;">
            <ul class="nav nav-list">
              <li><a href="#">Idioma</a></li>
              <li><a href="#">Perfil</a></li>
            </ul>
          </div>
        </li>

  

       
      </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
  </div>
 

@endsection

resources/views/layouts/navbar.blade.php
<div id="sidebar" class="sidebar responsive ace-save-state" data-sidebar="true" data-sidebar-scroll="true" 
	 data-sidebar-hover="true">
	<script type="text/javascript">
		try{ace.settings.loadState('sidebar')}catch(e){}
	</script>

	<ul class="nav nav-list" style="top: 0px;">
		<li class="active li-alt">
			<a href="{{ url('/home') }}" class="lev">
				<span class="menu-text"> Syxgem </span>
				<img src="{{ asset('assets/images/ICON-SYXIMAGO.png') }}" alt="" height="35" align="right">
			</a>
			<b class="arrow"></b>
		</li>
		<li class="">
			<a href="#" class="dropdown-toggle">
				<i class="menu-icon fa fa-suitcase"></i>
				<span class="menu-text">Proyectos</span>
				<b class="arrow fa fa-angle-down"></b>
			</a>
			<b class="arrow"></b>
			<ul class="submenu">
				<li class="">
					<a href="{{route('project.index')}}">
						<i class="menu-icon fa fa-caret-right"></i> Proyectos
					</a>
					<b class="arrow"></b>
				</li>
				<li class="">
					<a href="{{route('task.index')}}">
						<i class="menu-icon fa fa-caret-right"></i>Tareas
					</a>
					<b class="arrow"></b>
				</li>
				<li class="">
					<a href="mi-calendario.html">
						<i class="menu-icon fa fa-address-card"></i> Mi Calendario
					</a>
				</li>
			</ul>
		</li>


		<li class="">
			<a href="#" class="dropdown-toggle">
				<i class="menu-icon fa fa-address-card-o"></i>
				<span class="menu-text">Empleados</span>
				<b class="arrow fa fa-angle-down"></b>
			</a>
			<b class="arrow"></b>
			<ul class="submenu">

				<li class="">
					<a href="{{ route('employees.index') }}">
						<i class="menu-icon fa fa-caret-right"></i> General
					</a>
				</li>
				<li class="">
					<a href="{{ route('employees-department.index') }}">
						<i class="menu-icon fa fa-caret-right"></i> Por Departamento
					</a>
					<b class="arrow"></b>
				</li>
				<li class="">
					<a href="{{ route('employees-project.index')  }}">
						<i class="menu-icon fa fa-caret-right"></i> Por Proyecto
					</a>
					<b class="arrow"></b>
				</li>
			</ul>
		</li>


		<li class="">

			<a href="{{ route('department.index') }}" class="level-0">
				<i class="menu-icon fa fa-building-o"></i>
				<span class="menu-text"> Departamentos </span>
			</a>
		</li>
		<li class="">
			<a href="{{ route('charge.index') }}" class="level-0">
				<i class="menu-icon fa fa-calendar-check-o"></i>
				<span class="menu-text"> Cargos </span>
			</a>
			<b class="arrow"></b>
		</li>
		<li class="">
			<a href="{{route('documents.index')}}" class="level-0">
				<i class="menu-icon fa fa-folder"></i>
				<span class="menu-text"> Documentos </span>
			</a>
			<b class="arrow"></b>
		</li>
		<li class="li-alt">
			<a href="#" class="dropdown-toggle level-1">
				<span class="menu-text"> Chat </span>
				<i class="menu-icon fa fa-comments-o fa-lg"></i>
				<b class="arrow fa fa-angle-down"></b>
			</a>
			<b class="arrow"></b>
			<ul class="submenu">
				<li class="">
					<a href="chat-individual.html">
						<i class="menu-icon fa fa-caret-right"></i> Individual
					</a>
					<b class="arrow"></b>
				</li>
				<li class="">
					<a href="chat-grupal.html">
						<i class="menu-icon fa fa-caret-right"></i> Grupal
					</a>
					<b class="arrow"></b>
				</li>
			</ul>
		</li>
		<li class="li-alt">
			<a href="#" class="dropdown-toggle level-1">
				<span class="menu-text">Preferencias</span>
				<i class="menu-icon fa fa-cog fa-lg"></i>
				<b class="arrow fa fa-angle-down"></b>
			</a>
			<b class="arrow"></b>
			<ul class="submenu">
				<li class="">
					<a href="idioma.html">
						<i class="menu-icon fa fa-caret-right"></i> Idioma
					</a>
					<b class="arrow"></b>
				</li>
				<li class="">
					<a href="{{ route('user.index') }}">
						<i class="menu-icon fa fa-caret-right"></i> Perfil
					</a>
					<b class="arrow"></b>
				</li>
			</ul>
		</li>
	</ul><!-- /.nav-list -->
</div>